table dim_Industry
	lineageTag: fe1249a4-602c-4d94-a832-15581831fea7

	column Industry_Affected
		dataType: string
		lineageTag: 9f49b265-4c98-4e9a-a24d-b5bebe9bf3f0
		summarizeBy: none
		sourceColumn: Industry_Affected

		annotation SummarizationSetBy = Automatic

	column Industry_ID
		dataType: int64
		formatString: 0
		lineageTag: 34e5e7f9-7c8b-401d-b643-4bf0d94ea925
		summarizeBy: none
		sourceColumn: Industry_ID

		annotation SummarizationSetBy = Automatic

	partition dim_Industry = m
		mode: import
		source =
				let
				    Source = fact_raw,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"Industry_Affected"}),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Other Columns", "Index", 1, 1, Int64.Type),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Index",{{"Index", "Industry_ID"}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Renamed Columns",{"Industry_ID", "Industry_Affected"})
				in
				    #"Reordered Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

