table dim_Date
	lineageTag: 85bd114c-e283-4ff0-ba53-91badcca4e9a

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 17518a29-21f6-47aa-b980-defedd030e9a
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Year_ID
		dataType: int64
		formatString: 0
		lineageTag: 3b5f50e8-1037-4b4d-aa4c-aa0fedde3b67
		summarizeBy: none
		sourceColumn: Year_ID

		annotation SummarizationSetBy = Automatic

	partition dim_Date = m
		mode: import
		source =
				let
				    Source = fact_raw,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"Year"}),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Other Columns", "Index", 1, 1, Int64.Type),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Index",{{"Index", "Year_ID"}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Renamed Columns",{"Year_ID", "Year"})
				in
				    #"Reordered Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

